<a href="https://colab.research.google.com/github/jonathannghj/PyTorch-Deep-Learning/blob/main/00_pytorch_fundementals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundementals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch 
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.0.0+cu118


## Introductions to Tensor 

Creating tensors

PyTorch tensors are created using 'torch.Tensor()'

In [ ]:
# scalar
scalar = torch.tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])


In [ ]:
# ndim = number of brackets 
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

In [ ]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape


torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]
# Therefore, the 1 in [1, 3, 3] is the number of 3x3 matrices

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors 

Random Tensors are important because NNs start with full of random numbers and adjust those random numbers to better represent data

In [ ]:
# Creating random tensors of size/shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3555, 0.1395, 0.4129, 0.5406],
        [0.1830, 0.8778, 0.2566, 0.6459],
        [0.5114, 0.7129, 0.6932, 0.3218]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor2 = torch.rand(1, 3,4)
random_tensor2

tensor([[[0.0342, 0.0398, 0.9378, 0.5191],
         [0.3918, 0.6065, 0.3214, 0.6786],
         [0.2745, 0.2380, 0.3580, 0.7692]]])

In [ ]:
random_tensor2.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_tensor_mine = torch.rand(size=(5,4,1))
random_tensor_mine

tensor([[[0.0587],
         [0.3136],
         [0.7017],
         [0.8501]],

        [[0.4948],
         [0.7413],
         [0.6765],
         [0.8313]],

        [[0.9641],
         [0.0093],
         [0.9883],
         [0.9403]],

        [[0.6892],
         [0.9028],
         [0.8519],
         [0.7961]],

        [[0.5233],
         [0.8236],
         [0.3073],
         [0.9488]]])

In [ ]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange() of [0, 10)
one_to_thousand = torch.arange(start=1,end = 1000, step = 77)
one_to_thousand

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [ ]:
# Creating tensors like - you want to create a tensor, but to create a tensor with the same shape but dont want to input the data
ten_zeros = torch.zeros_like(input = one_to_thousand)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning

1. Tensors not right datatype
2. Tensors not right shape (tensor modification)
3. Tensors not on the right device

Check wikipedia for the precision in computing

Use 
1. .shape / .size() to determine shape
2. .dtype to determine dtype
3. .device to determine device

In [ ]:
#Float 32 tensor 
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor, defining the precision of the computing quantity detail(precision) vs memory
                               device=None, # can change it to "cuda". if operations are done between two tensors of different devices, there will be an error thrown
                               requires_grad=False) # whether anot to track gradients with respect to this tensor
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of precision

1. Element-wise multiplication
2. Matrix Multiplication

There are two main rules:
1. The **inner dimensions** must match
* '(3, 2) @ (3, 2)' won't work
* '(2, 3) @ (3, 2)' will work
* '(3, 2) @ (2, 3)' will work

2. The resulting matrix has the shape of the **outer dimensions**
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

To transpose, just perform .T to adjust the shapes

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor


tensor(14)

### Finding the min, max, mean, sum, etc. (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
# note: torch.mean or .mean() requires a datatype of float32 to work
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.sum()


tensor(450)

### Finding the positional min/max 
* use .argmin()/ .argmax()

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other or side by side
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped in certain way)
concatenating a sequence of tensors

In [ ]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# the original shape should have the same 

x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# using view. Changing z into x ( because a view of a tensor shares the same memory as the original)

z = x.view(5,2)
z, z.shape


(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
# Stack tensors on top of each other, dim 0 or dim 1 changes whether side by side or on top of another
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
 # Squeeze removes all the 1 dimension from a tensor
 x_squeezed = x_reshaped.squeeze()
 x_squeezed, x_squeezed.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Unsqueeze adds a single dimension to a target tensor at a specific dimension (dim)
x_unsqueezed = x_squeezed.unsqueeze(dim=1) # dim = 0 = adding dimension to the 0th index, dim = 1 = adding dimension to the 1st index
x_unsqueezed, x_unsqueezed.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [ ]:
# permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3))
x_original.size()


torch.Size([224, 224, 3])

In [ ]:
x_permute = x_original.permute(2,1,0)
x_permute

tensor([[[0.3601, 0.1296, 0.9540,  ..., 0.7306, 0.6299, 0.5242],
         [0.0882, 0.3051, 0.5589,  ..., 0.4605, 0.8121, 0.1918],
         [0.0877, 0.2143, 0.7799,  ..., 0.6171, 0.2716, 0.3653],
         ...,
         [0.5204, 0.8854, 0.7806,  ..., 0.3511, 0.4960, 0.1262],
         [0.0717, 0.5647, 0.4405,  ..., 0.5176, 0.9236, 0.6208],
         [0.6779, 0.6660, 0.0132,  ..., 0.0754, 0.7418, 0.2227]],

        [[0.4650, 0.2951, 0.0896,  ..., 0.9057, 0.5100, 0.7701],
         [0.6368, 0.7100, 0.8412,  ..., 0.4312, 0.3087, 0.0958],
         [0.8444, 0.0196, 0.5034,  ..., 0.6485, 0.1119, 0.4355],
         ...,
         [0.2382, 0.9808, 0.7629,  ..., 0.0917, 0.7280, 0.0126],
         [0.3861, 0.1713, 0.0128,  ..., 0.1985, 0.7882, 0.4986],
         [0.3677, 0.3353, 0.7293,  ..., 0.3277, 0.8820, 0.3233]],

        [[0.3073, 0.3159, 0.9236,  ..., 0.6911, 0.0470, 0.6102],
         [0.6026, 0.8315, 0.3500,  ..., 0.6030, 0.1772, 0.2779],
         [0.5728, 0.1428, 0.2714,  ..., 0.8038, 0.7505, 0.

In [ ]:
# Indexing 
x_original[0,0,0] = 7321
x_original[0,0,0], x_permute[0,0,0]

(tensor(7321.), tensor(7321.))

### Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)

In [ ]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
# ":" is used to select all from the target dimension
x[:, 0]


tensor([[1, 2, 3]])

In [ ]:
# all values of 0th and 1st but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0th dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1] # 0 or : works same here

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dim and all from 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[:,2,2]

tensor([9])

In [ ]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch tensors & NumPy

NumPy is a popular scientific numerical computing library
PyTorch has functionality to interact with it.

* data in Numpy, want in PyTorch tensor -> 'torch.from_numpy(ndarray)'
* data in PyTorch tensor, want Numpy -> 'torch.Tensor.numpy()'

In [ ]:
# note that default dtype is float32, but for nparray its float64. to convert, simply use .type(torch.float32)
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy to pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
array = array+1

In [ ]:
array

array([2., 3., 4., 5., 6., 7., 8.])

In [ ]:
tensor # tensor is a separate memory unlike view

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

 ## Reproducibility (trying to take random out of random)
 
 In short how a nn works:
 start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data again and again

 To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

 Essentially what the random seed does is "flavour" the randomness.

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0601, 0.2751, 0.1307, 0.5511],
        [0.3711, 0.0790, 0.9434, 0.0361],
        [0.1271, 0.9867, 0.1539, 0.6980]])
tensor([[0.5035, 0.3635, 0.1497, 0.9321],
        [0.9542, 0.0828, 0.5800, 0.8938],
        [0.2942, 0.1416, 0.0248, 0.3166]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# making a random but reproducible tensors
# using random seed

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
## Reproducibility in Pytorch IMPORTANT

## Running tensors and PyTorch objects on the GPUs (making faster computations)

GPU = faster computation on numbers thanks to CUDA + NVIDIA hardware + Pytorch

1. Google Collab 
2. Own setup
3. Use Cloud Computing Google Cloud Computing, AWS

## Putting tensors (and models) on the GPU
We want to use GPU as it results in faster computations

tensor([1, 2, 3]) cpu


False

In [ ]:
!nvidia-smi

Thu May  4 02:16:59 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch 
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


### Adding tensors (and models) on the GPU
### tensors back to the CPU because numpy only works on CPU

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])